// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240922095854_UniqueName")]
    partial class UniqueName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Entity.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MainId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subdivisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Подразделение"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            MainId = 1,
                            Name = "Часть подразделения"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MainId = 4,
                            Name = "Часть отдела"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Отдел"
                        });
                });

            modelBuilder.Entity("WebApi.Entity.Subdivision", b =>
                {
                    b.HasOne("WebApi.Entity.Subdivision", "Main")
                        .WithMany()
                        .HasForeignKey("MainId");

                    b.Navigation("Main");
                });
#pragma warning restore 612, 618
        }
    }
}
